milestone: # empty path for not init
# milestone: ./output/ShapenetCar128_mlp_g128_d6/model_inner_test.pt
model_comment: 'ShapenetCar128_mlp_g128_d6'

# constant
image_shape: &image_shape 128
hypo_hiddim: &hidden_dim 512
hypo_depth: &hypo_depth 6
# training para
train_num_steps: 100000
save_every: 1000
## NOTE: THE SIZE OF "batch_size * gradient_accumulate_every" 
##       must be large enough for nerf training, recommend > 20
batch_size: 6
gradient_accumulate_every: 3
coord_noise: False
opt_type: "adam" # adam, rmsprop
loss_type: &loss_type l2 # l1 or l2
train_lr: 0.00005
# nerf target
train_target: &train_target nerf
train_n_rays: 512


hyper_network: &hyper_network [
  "HyperNetwork",
  {
    n_groups: 128, # use mininum int for disable grouping
    direct_wtoken: False, # weight grouping setting
    grouping_mode: "mlp", # "mlp", "mlp_mod"
    tokenizer: {
      name: "nvs_tokenizer",
      args: {
        input_size: *image_shape,
        patch_size: 8, # 9,4
        dim: *hidden_dim,
      }
    },
    hyponet: {
      name: &hyponet_name "hypo_nerf",
      args: &hpnet_params {
        use_viewdirs: False,
        depth: *hypo_depth,
        hidden_dim: *hidden_dim,
        use_pe: True,
        pe_dim: 128,
        pe_sigma: 512,
      }
    },
    tinr_enc: {
      name: "TInrEncoder",
      args: {
        shortcut_every: 0,
        dim: *hidden_dim,
        depth: &enc_depth 6,
        n_head: 6,
        head_dim: 64,
        ff_dim: 3072,
        dropout: 0.,
      }
    },
    tinr_dec: {
      name: "TInrDecoder",
      args: {
        dim: *hidden_dim,
        depth: 6,
        n_head: 6,
        head_dim: 64,
        ff_dim: 3072,
        dropout: 0.,
      }
    },
  }
]


model_framework: {
  frame_work: "NormalINR",
  inner_model: *hyper_network,
  outer_model: [
    "ModelMangager",
    {
      image_shape: *image_shape,
      loss_type: *loss_type,
      target: *train_target,
    }
  ]
}

dataset_kwargs: [
  "learnit_shapenet",
  {
    root_path: '/data1/open_datasets/learnit_shapenet/',
    category: 'cars',
    split: 'train',
    views_rng: [0, 25],
    n_support: 3,
    n_query: 1,
    repeat: 2,
  }
]